### PR TITLE
Fix 67 - Suggested changes for use with current-based synapses

### PR DESCRIPTION
**Pull request by torbjone**
Taking over from #66 intended to solve #67

### CODE REVIEW

**Comment by torbjone** [comment]
@espenhgn Are you OK with merging, or do we need to look more into this? There are still some questions in #66, but I'm not sure if you have had the time to look more at them?

**Comment by espenhgn** [comment]
> @espenhgn Are you OK with merging, or do we need to look more into this? There are still some questions in #66, but I'm not sure if you have had the time to look more at them?

No, not really ;-)
I'll try tonight. Let's not merge this yet with multiple "TODO"s etc. in the code.

**Comment by torbjone** [comment]
I cleaned up the documentation a bit, and removed outdated TODOs. Can you have a look?

**Review by espenhgn — APPROVED** [review]
Looks great! 
Just squash-merge if you're done

**Pull request merged**
